# Backstage override configuration for your local development environment
catalog:
  locations:
    - type: file
      target: /mood-backstage/scaffolder-templates/catalog-info.yaml

backend:
  baseUrl: http://localhost:7007
  reading:
    allow:
      - host: localhost
        ports: [7007]
      - host: 127.0.0.1
        ports: [7007]
      - host: ::1
      - host: raw.githubusercontent.com
      - host: github.com
        
      
proxy:
  endpoints:
    '/mood':
      target: 'http://127.0.0.1:61810'
      changeOrigin: true
