apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: mood-templates
  title: Mood Templates
  description: A collection of templates for mood submission and management
spec:
  type: url
  path: https://raw.githubusercontent.com/tanisha0016/mood-backstage/main/scaffolder-templates/mood-form.yaml
  owner: tanisha
  lifecycle: experimental
  