apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mood-form
  title: Mood Form
  description: Submit your mood and name
  owner: user:guest
spec:
  type: service

  parameters:
    - title: Mood Submission
      required:
        - name
        - mood
      properties:
        name:
          type: string
          title: Your Name
          description: Enter your name
        mood:
          type: string
          title: Mood
          enum:
            - Happy
            - Sad
            - Neutral
            - Excited
            - Anxious
          enumNames:
            - Happy 
            - Sad
            - Neutral
            - Excited
            - Anxious
          
          description: Select your current mood

  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          mood: ${{ parameters.mood }}
          timestamp: "${{ now | date: '%Y-%m-%dT%H:%M:%SZ' }}"

    # This step publishes the contents of the working directory to GitHub.
    # If you or your organization prefer another default branch name over 'main'
    # you can change that here.
    # - id: publish
    #   name: Publish
    #   action: publish:github
    #   input:
    #     allowedHosts: ['github.com']
    #     description: This is ${{ parameters.name }}
    #     repoUrl: ${{ parameters.repoUrl }}
    #     defaultBranch: 'main'

    # The final step is to register our new component in the catalog.
    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     #repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
    #     catalogInfoUrl: https://raw.githubusercontent.com/tanisha0016/demo-project/main/backstage-template/catalog-info.yaml

    - id: send-to-api
      name: Send mood to Go producer
      action: http:backstage:request
      input:
        method: POST
        path: '/api/mood-plugin/submit'
        headers:
          Content-Type: application/json
          Authorization: ""
        body:
          name: ${{ parameters.name }}
          mood: ${{ parameters.mood }}
          timestamp: "${{ now | date: '%Y-%m-%dT%H:%M:%SZ' }}"

        logRequestBody: true
        logResponseBody: true
        continueOnBadResponse: true
        logLevel: 'debug'

    # - id: send-to-api
    #   name: Send mood to go producer
    #   action: http:backstage:request
    #   input:
    #     method: POST
    #     path: '/api/proxy/mood'
    #     headers:
    #       Content-Type: application/json
    #     body:
    #       name: ${{ parameters.name }}
    #       mood: ${{ parameters.mood }}


        # auth: false
        # token: null

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    text:
      - title: Mood submitted to Go producer
        content: "Thanks for submitting your mood!"
